project:
  type: website
  output-dir: docs

website:
  sidebar: true
  
  
repo-url: https://github.com/elizabeth-hirsch/skeena-sockeye-inseason-updates.git

downloads: [pdf]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: visual

