project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents: 
      - text: "Skeena Salmon In-Season Update for SFNTC"
        href: skeena-salmon-inseason-updates.qmd
      
  
  
repo-url: https://github.com/elizabeth-hirsch/skeena-sockeye-inseason-updates.git

downloads: [pdf]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: visual

