---
title: "Skeena Salmon In-Season Update"
subtitle: "June 11, 2025"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r load libraries, include=FALSE}
library(tidyverse)
library(data.table)
library(readxl)
library(knitr)
library(ggpubr)
library(kableExtra)

options(scipen=10000)
```

```{r load 2025 data and format, include=FALSE}
# data<-read_excel("data/Tyee data 2025.xlsx",sheet="Tyee") %>%
#   mutate(Date = as.Date(Date))
# 
# com_catch <- read_excel("data/commercial catch 2025", sheet = "catch") %>%
#   pivot_longer(4:10,names_to="Species",values_to="Catch")%>%
#   mutate(cpue=Catch/effort)%>%
#   #filter(Date>as.Date("2024-07-05")&Date<as.Date("2024-08-10"))%>%
#   mutate(type=ifelse(Species%in%c("Chinook (Released)","Chum (Released)","Steelhead (Released)","Coho (Released)"),"Released","Kept"))%>%
#   mutate(sp=case_when(Species=="Chinook (Released)"~"Chinook",
#                       Species=="Coho (Released)"~"Coho",
#                       Species=="Pink (Kept)"~"Pink",
#                       Species=="Pink (Released)"~"Pink",
#                       Species=="Chum (Released)"~"Chum",
#                       Species=="Steelhead (Released)"~"Steelhead",
#                       Species=="Sockeye (Kept)"~"Sockeye"),
#          dis=case_when(Species=="Chinook (Released)"~"Released",
#                       Species=="Coho (Released)"~"Released",
#                       Species=="Pink (Kept)"~"Kept",
#                       Species=="Pink (Released)"~"Released",
#                       Species=="Chum (Released)"~"Released",
#                       Species=="Steelhead (Released)"~"Released",
#                       Species=="Sockeye (Kept)"~"Kept"))
# 
# fn_catch <- read_excel("data/FNs catch 2025.xlsx", sheet = "demo catches")
```

```{r set days, echo=FALSE}
# tyee.day<-as.Date("2024-09-22")
# tyee.date<-"September 22"
# fence.day<-as.Date("2024-09-22")
# fence.date<-"September 22"
# today<-as.Date("2024-09-22")
```
